experiment: cifar10_fedloge_dir01_if50
script: fedloge.py
args:
  dataset: cifar10
  model: resnet18
  alpha_dirichlet: 0.1
  IF: 0.02
  beta: 0
  gpu: 0
  num_users: 40
  frac: 1.0
  ghead: g_head
  thre: 5
  noisecal: 300
  noisestart: 500
  rounds: 550
  loss_type: CE
