experiment: cifar100_fedloge_dir01_if50
script: fedloge_100.py
args:
  dataset: cifar100
  model: resnet34
  alpha_dirichlet: 0.1
  IF: 0.02
  beta: 0
  gpu: 0
  num_users: 10
  frac: 1.0
  ghead: g_head
  thre: 20
  noisecal: 300
  noisestart: 500
  rounds: 550
  loss_type: CE
